# Generated by Django 6.0.2 on 2026-02-15 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0002_order_company_order_notes_order_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
